language: bash

services:
  - docker

script:
  - docker run --rm -v $(pwd):/root/sources -w /root/sources maven:3.3.9-jdk-8 mvn clean install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

after_success:
  - if [ "$TRAVIS_TAG" ]; then
    docker build -t jeci/alfresco-platform-ceph-rados:$TRAVIS_TAG -t jeci/alfresco-platform-ceph-rados:latest alfresco-ceph-rados;
    docker build -t jeci/alfresco-platform-openio:$TRAVIS_TAG -t jeci/alfresco-platform-openio:latest alfresco-openio;
    docker build -t jeci/alfresco-platform-swift:$TRAVIS_TAG -t jeci/alfresco-platform-swift:latest alfresco-swift;
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push jeci/alfresco-platform-ceph-rados;
    docker push jeci/alfresco-platform-openio;
    docker push jeci/alfresco-platform-swift;
    fi

deploy:
  provider: releases
  api_key:
    secure: GdwzvHcDmW8RZZZzG6FCRMEf/whE9ER1HukxEQNHPuVS+PCCb9hmsCgyauMP7MvL72GCJ+IB13f2x3BYRjdnG8n9yszUlgYvjYeEKCa58GmnDeHUxd+WS3ireZJhnYBSkLN920PI1WUjczye9d/9Tzma+1j2xTt+SPvmDmYueRQ3gulP1119lGJSdicitBh9xTExSwyPVLrhG1z6KHGFOQE7G5c/iiIoZXgErmzak6acp/HwErGYBAcDAOPLZsazzyyoGrnydbyyTWyQxGhOz1cJ0VPF2POnAgQ/GWGPQTBvOaDqN+XVUMTH1eZ6At6OsOI1GI2UqrN10u7WLClWP6KWetXgL6vaG9DztR3O7XO/EyfSEBua1BX4hiiCdd7nkMVWNAIkkntuDpqGSNthejaLYTS6TXWnLydD33ScVSV+XeL+2gyH5E1GT94mGleZvi0jyzglwGoAxLwN+w6ZWNEkymN5Qm+F7hGvWRv2HsqafPENnK9m/tpqJ2TC8X8gEjVIo9DspCChLphkhYTHZBVj0CitSJIUaHvZEqGkU/emorSHEhXNf1smkYpCg0/kJ2OkNYTO9pKY1e+WCrtHM4+t5Zkng3lNePx11s0Qm8bscQZSllCWe0IRMWb2FMbrYUWEC98W7CK/7AiH5PS7P6dv5h+bY2BRP38iWnSVqDk=
  file:
    - "alfresco-ceph-rados/target/*.amp"
    - "alfresco-openio/target/*.amp"
    - "alfresco-swift/target/*.amp"
  file_glob: true
  skip_cleanup: true
  on:
    repo: jeci-sarl/alfresco-object-storage-connectors
    tags: true
